version: '3.8'

networks:
  default:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: .
    volumes:
      - type: 'bind'
        source: './'
        target: '/app'
    ports:
      - "3001:3001"
    networks:
      - default
    command: "npm run dev:server"